[terminal]
vt = 1

[initial_session]
command = "/usr/bin/start-hyprland"
user = "awe"

# Fallback if initial_session (Hyprland) crashes
[default_session]
command = "tuigreet --cmd /usr/bin/start-hyprland --remember"
user = "greeter"
